In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import os
from pathlib import Path

from tqdm.autonotebook import tqdm

/tmp/ipykernel_6278/1290320258.py:9: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

In [2]:
# The goal of this notebook is to pick a handful of households from
# the data set while ending up with as minimum Nan as possible!

In [3]:
# We are using already clean data.!
source_data = Path("./london_dataset/")
block_data_path = source_data/'halfhourly_dataset'/'halfhourly_dataset'

In [4]:
household_names = np.load('householdnames.npz',allow_pickle=True)
selected_households = household_names['selected_households']

In [5]:
"""We go over the csv files once again and this time only pick 
household that have the desired end date and length.
We save the data into a wide format for later use"""
list_selected_household = []
for f in tqdm(block_data_path.glob("*.csv")):
    df = pd.read_csv(f, parse_dates=False, dtype='object')
    # to be safe 
    df['tstp'] = pd.to_datetime(df['tstp'], yearfirst=True) 
    # check if the LCLid in the selected housholds
    df = df[df.LCLid.isin(selected_households)]
    # Turn the date into wide format
    df_pivoted = df.pivot(values='energy(kWh/hh)', columns='LCLid', index='tstp')
    # drop the NA
    df_pivoted = df_pivoted.dropna(axis=0)
    list_selected_household.append(df_pivoted)

0it [00:00, ?it/s]

112it [02:37,  1.41s/it]

In [6]:
df_selected_households = pd.concat(list_selected_household, axis=1)

df_selected_households

LCLid,MAC004113,MAC004125,MAC004177,MAC001531,MAC001559,MAC001431,MAC001459,MAC001503,MAC001527,MAC001540,...,MAC001384,MAC001387,MAC001411,MAC001412,MAC001416,MAC001424,MAC004068,MAC001335,MAC004130,MAC004138
tstp,,,,,,,,,,,,,,,,,,,,,
2012-05-08 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-05-08 09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-05-08 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-05-08 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-05-08 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-02-27 22:00:00,0.228,0.126,0.047,0.244,0.184,0.088,0,0.074,0.14,0.204,...,0.609,0.057,0.376,0.097,0.117,0.115,0.22,0.099,0.482,0.223
2014-02-27 22:30:00,0.163,0.132,0.032,0.18,0.152,0.081,0,0.08,0.074,0.22,...,0.312,0.115,0.405,0.039,0.105,0.091,0.341,0.057,0.425,0.299
2014-02-27 23:00:00,0.062,0.047,0.031,0.19,0.157,0.091,0,0.067,0.06,0.153,...,0.296,0.058,0.357,0.039,0.127,0.012,0.177,0.099,0.375,0.09
2014-02-27 23:30:00,0.053,0.076,0.048,0.151,0.226,0.101,0,0.046,0.017,0.175,...,0.3,0.055,0.212,0.072,0.096,0.01,0.08,0.13,0.351,0.077
2014-02-28 00:00:00,0.073,0.033,0.031,0.108,0.153,0.071,0,0.054,0.034,0.119,...,0.308,0.109,0.146,0.101,0.103,0.009,0.041,0.114,0.148,0.036

In [7]:
df_selected_households = df_selected_households.dropna(axis=0)
# drop the Nan

df_selected_households

LCLid,MAC004113,MAC004125,MAC004177,MAC001531,MAC001559,MAC001431,MAC001459,MAC001503,MAC001527,MAC001540,...,MAC001384,MAC001387,MAC001411,MAC001412,MAC001416,MAC001424,MAC004068,MAC001335,MAC004130,MAC004138
tstp,,,,,,,,,,,,,,,,,,,,,
2012-05-22 14:30:00,0.051,0.234,0.091,0.127,0.129,0.417,0.06,0.123,0.178,0.273,...,0.064,0.126,0.193,0.044,0.088,0.012,0.128,0.047,0.379,0.071
2012-05-22 15:00:00,0.058,0.114,0.092,0.233,0.114,0.829,0.267,0.1,0.098,0.073,...,0.065,0.147,0.138,0.114,0.096,0.026,0.15,0.014,0.819,0.108
2012-05-22 15:30:00,0.056,0.056,0.089,0.125,0.192,0.499,0.137,0.118,0.094,0.089,...,0.04,0.176,0.162,0.076,0.101,0.044,0.123,0.091,0.336,0.102
2012-05-22 16:00:00,0.053,0.043,0.084,0.122,0.158,0.203,0.069,0.119,0.108,0.127,...,0.017,0.175,0.123,0.226,0.083,0.012,0.088,0.057,0.363,0.074
2012-05-22 16:30:00,0.045,0.142,0.236,0.201,0.312,0.273,0.276,0.097,0.292,0.11,...,0.017,0.173,0.115,0.251,0.114,0.011,0.111,0.042,0.408,0.119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-02-27 22:00:00,0.228,0.126,0.047,0.244,0.184,0.088,0,0.074,0.14,0.204,...,0.609,0.057,0.376,0.097,0.117,0.115,0.22,0.099,0.482,0.223
2014-02-27 22:30:00,0.163,0.132,0.032,0.18,0.152,0.081,0,0.08,0.074,0.22,...,0.312,0.115,0.405,0.039,0.105,0.091,0.341,0.057,0.425,0.299
2014-02-27 23:00:00,0.062,0.047,0.031,0.19,0.157,0.091,0,0.067,0.06,0.153,...,0.296,0.058,0.357,0.039,0.127,0.012,0.177,0.099,0.375,0.09
2014-02-27 23:30:00,0.053,0.076,0.048,0.151,0.226,0.101,0,0.046,0.017,0.175,...,0.3,0.055,0.212,0.072,0.096,0.01,0.08,0.13,0.351,0.077
2014-02-28 00:00:00,0.073,0.033,0.031,0.108,0.153,0.071,0,0.054,0.034,0.119,...,0.308,0.109,0.146,0.101,0.103,0.009,0.041,0.114,0.148,0.036

In [8]:

for column in df_selected_households.columns:
    df_selected_households.loc[:,column] = df_selected_households[column].astype('float')

df_selected_households.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 25506 entries, 2012-05-22 14:30:00 to 2014-02-28 00:00:00
Columns: 392 entries, MAC004113 to MAC004138
dtypes: object(392)
memory usage: 76.5+ MB

In [9]:
# save some memory
del list_selected_household, df, df_pivoted

In [10]:
# resmaple to turn it into hourly data !!!
df_selected_households = df_selected_households.resample('60min', closed='right').sum() 
df_selected_households.head()

LCLid,MAC004113,MAC004125,MAC004177,MAC001531,MAC001559,MAC001431,MAC001459,MAC001503,MAC001527,MAC001540,...,MAC001384,MAC001387,MAC001411,MAC001412,MAC001416,MAC001424,MAC004068,MAC001335,MAC004130,MAC004138
tstp,,,,,,,,,,,,,,,,,,,,,
2012-05-22 14:30:00,0.051,0.234,0.091,0.127,0.129,0.417,0.06,0.123,0.178,0.273,...,0.064,0.126,0.193,0.044,0.088,0.012,0.128,0.047,0.379,0.071
2012-05-22 15:00:00,0.058,0.114,0.092,0.233,0.114,0.829,0.267,0.1,0.098,0.073,...,0.065,0.147,0.138,0.114,0.096,0.026,0.15,0.014,0.819,0.108
2012-05-22 15:30:00,0.056,0.056,0.089,0.125,0.192,0.499,0.137,0.118,0.094,0.089,...,0.04,0.176,0.162,0.076,0.101,0.044,0.123,0.091,0.336,0.102
2012-05-22 16:00:00,0.053,0.043,0.084,0.122,0.158,0.203,0.069,0.119,0.108,0.127,...,0.017,0.175,0.123,0.226,0.083,0.012,0.088,0.057,0.363,0.074
2012-05-22 16:30:00,0.045,0.142,0.236,0.201,0.312,0.273,0.276,0.097,0.292,0.11,...,0.017,0.173,0.115,0.251,0.114,0.011,0.111,0.042,0.408,0.119

In [11]:
print(f"Total memory usage: {df_selected_households.memory_usage().sum()/1024**2} MB")

Total memory usage: 76.47596740722656 MB

In [12]:
# renaming the index before saving
df_selected_households.index.name = 'date'
df_selected_households.columns.name=''
# save the data
df_selected_households.to_csv('./london_dataset/london_electricity.csv', index=True)

In [13]:
df_selected_households

,MAC004113,MAC004125,MAC004177,MAC001531,MAC001559,MAC001431,MAC001459,MAC001503,MAC001527,MAC001540,...,MAC001384,MAC001387,MAC001411,MAC001412,MAC001416,MAC001424,MAC004068,MAC001335,MAC004130,MAC004138
date,,,,,,,,,,,,,,,,,,,,,
2012-05-22 14:30:00,0.051,0.234,0.091,0.127,0.129,0.417,0.06,0.123,0.178,0.273,...,0.064,0.126,0.193,0.044,0.088,0.012,0.128,0.047,0.379,0.071
2012-05-22 15:00:00,0.058,0.114,0.092,0.233,0.114,0.829,0.267,0.1,0.098,0.073,...,0.065,0.147,0.138,0.114,0.096,0.026,0.15,0.014,0.819,0.108
2012-05-22 15:30:00,0.056,0.056,0.089,0.125,0.192,0.499,0.137,0.118,0.094,0.089,...,0.04,0.176,0.162,0.076,0.101,0.044,0.123,0.091,0.336,0.102
2012-05-22 16:00:00,0.053,0.043,0.084,0.122,0.158,0.203,0.069,0.119,0.108,0.127,...,0.017,0.175,0.123,0.226,0.083,0.012,0.088,0.057,0.363,0.074
2012-05-22 16:30:00,0.045,0.142,0.236,0.201,0.312,0.273,0.276,0.097,0.292,0.11,...,0.017,0.173,0.115,0.251,0.114,0.011,0.111,0.042,0.408,0.119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-02-27 22:00:00,0.228,0.126,0.047,0.244,0.184,0.088,0.0,0.074,0.14,0.204,...,0.609,0.057,0.376,0.097,0.117,0.115,0.22,0.099,0.482,0.223
2014-02-27 22:30:00,0.163,0.132,0.032,0.18,0.152,0.081,0.0,0.08,0.074,0.22,...,0.312,0.115,0.405,0.039,0.105,0.091,0.341,0.057,0.425,0.299
2014-02-27 23:00:00,0.062,0.047,0.031,0.19,0.157,0.091,0.0,0.067,0.06,0.153,...,0.296,0.058,0.357,0.039,0.127,0.012,0.177,0.099,0.375,0.09
2014-02-27 23:30:00,0.053,0.076,0.048,0.151,0.226,0.101,0.0,0.046,0.017,0.175,...,0.3,0.055,0.212,0.072,0.096,0.01,0.08,0.13,0.351,0.077
2014-02-28 00:00:00,0.073,0.033,0.031,0.108,0.153,0.071,0.0,0.054,0.034,0.119,...,0.308,0.109,0.146,0.101,0.103,0.009,0.041,0.114,0.148,0.036